title: Synthesis Wiki
description: Documentação Oficial do Mod Synthesis para Minecraft.
theme: just-the-docs
url: https://wolfhydra.github.io/synthesis  # Substitui pelo teu link real depois
aux_links:
  "Baixar no CurseForge": https://curseforge.com/
  "GitHub Repo": https://github.com/teu-usuario/synthesis

# Configuração do Menu Lateral
back_to_top: true
search_enabled: true

# Ativar o tema remoto (para funcionar no GitHub sem instalar nada)
remote_theme: just-the-docs/just-the-docs